give @s createb:andesite_casing 32
give @s createb:cogwheel 16
give @s createb:shaft 32
give @s createb:gearbox 16
give @s createb:propeller 8
give @s createb:bearing 16
give @s createb:balloon_fabric 32
give @s createb:wrench 1
give @s createb:wind_bearing 8
give @s createb:propeller_controller 4
give @s createb:ballast_tank 16
